<?php
$eventName = setting($pdo, 'event_name', 'Retiro 2027 - ICNV Catedral');
$mealTypes = rt2027_food_meal_types();
$groupedMeals = $foodReportMeals ?? [];
$summary = $foodReportSummary ?? [];
$rawJson = json_encode($groupedMeals, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
?><!DOCTYPE html>
<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= h($eventName) ?> • Relatório das refeições</title>
<style>
:root{--bg:#f4f8f7;--surface:#fff;--text:#1f2937;--muted:#6b7280;--line:#dbe5e3;--brand:#0f766e;--brand-soft:#d1fae5;--shadow:0 10px 30px rgba(15,23,42,.08);--radius:18px}.wrap{max-width:1150px;margin:0 auto;padding:20px 14px 40px}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,Arial,sans-serif;background:radial-gradient(circle at top right, rgba(15,118,110,.10), transparent 28%),var(--bg);color:var(--text)}.hero{background:linear-gradient(135deg,#0b3d3a 0%, #0f766e 100%);color:#fff;border-radius:26px;padding:24px 18px;box-shadow:var(--shadow)}.hero h1{margin:0 0 8px;font-size:clamp(28px,5vw,42px);line-height:1.05;letter-spacing:-.03em}.hero p{margin:0;color:rgba(255,255,255,.88)}.pill-row{display:flex;flex-wrap:wrap;gap:10px;margin-top:18px}.pill{background:rgba(255,255,255,.13);border:1px solid rgba(255,255,255,.12);border-radius:999px;padding:10px 14px;font-size:14px}.toolbar{position:sticky;top:0;z-index:5;margin:18px 0 14px;background:rgba(244,248,247,.92);backdrop-filter:blur(10px);padding:12px 0}.toolbar-inner{display:flex;gap:10px;flex-wrap:wrap;align-items:center}.search{flex:1 1 260px;border:1px solid var(--line);border-radius:16px;background:var(--surface);padding:14px 16px;font-size:15px;color:var(--text)}button{font:inherit;border:0;cursor:pointer}.segmented{display:flex;gap:8px;flex-wrap:wrap}.segmented button{padding:11px 14px;border-radius:999px;background:var(--surface);border:1px solid var(--line);color:var(--muted)}.segmented button.active{background:var(--brand);border-color:var(--brand);color:#fff}.grid{display:grid;gap:14px}.cards{grid-template-columns:repeat(auto-fit,minmax(320px,1fr))}.card{background:var(--surface);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);padding:18px}.card h3{margin:0 0 8px;font-size:22px}.muted{color:var(--muted);font-size:14px}.meta-row{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.badge{display:inline-flex;align-items:center;gap:6px;font-size:13px;padding:8px 10px;border-radius:999px;background:#f5f7f8;color:var(--muted);border:1px solid var(--line)}.badge.primary{background:var(--brand-soft);border-color:transparent;color:var(--brand);font-weight:700}.list{list-style:none;padding:0;margin:16px 0 0;display:grid;gap:10px}.list li{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;border-top:1px solid var(--line);padding-top:10px}.left{min-width:0}.name{font-weight:700;font-size:14px}.sub{color:var(--muted);font-size:13px;margin-top:2px}.qty{font-weight:700;font-size:14px;color:var(--brand);white-space:nowrap}.diff-plus{color:#b91c1c}.diff-minus{color:#047857}.counter{margin:8px 0 0;color:var(--muted);font-size:14px}.summary{display:none}.summary.visible,.families.visible{display:block}.footer{margin-top:18px;text-align:center;color:var(--muted);font-size:13px}@media(max-width:720px){.card{padding:16px}.list li{flex-direction:column;align-items:flex-start}}
</style></head><body><div class="wrap"><header class="hero"><h1><?= h($eventName) ?></h1><p>Relatório interativo das refeições do retiro, com previsto x executado, histórico de preparo e consumo dos ingredientes.</p><div class="pill-row"><span class="pill">🍽 <?= (int)($summary['meals'] ?? 0) ?> refeição(ões)</span><span class="pill">📅 <?= (int)($summary['days'] ?? 0) ?> dia(s)</span><span class="pill">👥 <?= (int)($summary['planned_people'] ?? 0) ?> pessoas previstas</span><span class="pill">✅ <?= (int)($summary['executed_people'] ?? 0) ?> pessoas executadas</span><span class="pill">⚖️ Diferença total <?= rt2027_format_quantity(($summary['diff_total'] ?? 0), 'un') ?></span></div></header><div class="toolbar"><div class="toolbar-inner"><input id="searchInput" class="search" type="search" placeholder="Buscar por refeição, dia, responsável, item ou ingrediente"><div class="segmented"><button class="active" data-view="meals">Por refeição</button><button data-view="summary">Resumo por dia</button></div></div><p id="counterText" class="counter"></p></div><section id="mealsSection" class="families visible"><div id="mealsGrid" class="grid cards"></div></section><section id="summarySection" class="summary"><div id="summaryGrid" class="grid cards"></div></section><p class="footer">Arquivo gerado automaticamente em <?= h($generatedAt ?? date('d/m/Y H:i')) ?> com base nos dados atuais do sistema.</p></div><script>
const RAW=<?= $rawJson ?: '[]' ?>;
const byDay={};
RAW.forEach(m=>{const d=m.day; if(!byDay[d]) byDay[d]={day:d, meals:0, planned_people:0, executed_people:0, planned_total:0, executed_total:0, items:[]}; byDay[d].meals++; byDay[d].planned_people += Number(m.estimated_people||0); byDay[d].executed_people += Number(m.executed_people || m.estimated_people || 0); byDay[d].planned_total += Number(m.planned_total||0); byDay[d].executed_total += Number(m.executed_total||0); byDay[d].items.push(m);});
function num(v){return new Intl.NumberFormat('pt-BR',{minimumFractionDigits:3,maximumFractionDigits:3}).format(Number(v||0));}
function dayLabel(d){return 'Dia ' + d;}
let view='meals', search='';
const mealsGrid=document.getElementById('mealsGrid'), summaryGrid=document.getElementById('summaryGrid'), counter=document.getElementById('counterText');
function renderMeals(){const rows=RAW.filter(m=>JSON.stringify(m).toLowerCase().includes(search)); mealsGrid.innerHTML=rows.map(m=>`<article class="card"><h3>${dayLabel(m.day)} · ${m.title}</h3><div class="muted">${m.meal_date||'—'} · ${m.meal_time||'--:--'} · ${m.responsible_name||'Sem responsável'}</div><div class="meta-row"><span class="badge primary">Previsto: ${m.estimated_people||0}</span><span class="badge">Executado: ${m.executed_people ?? m.estimated_people ?? 0}</span><span class="badge">Status: ${m.status}</span></div><ul class="list">${(m.items||[]).map(i=>`<li><div class="left"><div class="name">${i.menu_item_name||'Item sem nome'}</div><div class="sub">${i.pantry_item_name||'Sem ingrediente'} · ${i.consumption_mode==='per_person'?'por pessoa':'fixo'}</div></div><div class="qty">P: ${num(i.planned_quantity)} ${i.ingredient_unit||''}<br>E: ${num(i.executed_quantity)} ${i.ingredient_unit||''}<br><span class="${Number(i.quantity_diff||0)>0?'diff-plus':'diff-minus'}">Δ ${num(i.quantity_diff)} ${i.ingredient_unit||''}</span></div></li>`).join('') || '<li><div class="muted">Sem itens vinculados.</div></li>'}</ul></article>`).join(''); counter.textContent=`${rows.length} refeição(ões) exibida(s).`;}
function renderSummary(){const rows=Object.values(byDay).filter(d=>JSON.stringify(d).toLowerCase().includes(search)); summaryGrid.innerHTML=rows.map(d=>`<article class="card"><h3>${dayLabel(d.day)}</h3><div class="meta-row"><span class="badge primary">${d.meals} refeição(ões)</span><span class="badge">Previsto: ${d.planned_people}</span><span class="badge">Executado: ${d.executed_people}</span></div><ul class="list"><li><div class="left"><div class="name">Consumo total previsto</div></div><div class="qty">${num(d.planned_total)}</div></li><li><div class="left"><div class="name">Consumo total executado</div></div><div class="qty">${num(d.executed_total)}</div></li><li><div class="left"><div class="name">Diferença</div></div><div class="qty ${Number(d.executed_total-d.planned_total)>0?'diff-plus':'diff-minus'}">${num(d.executed_total-d.planned_total)}</div></li></ul></article>`).join(''); counter.textContent=`${rows.length} resumo(s) exibido(s).`;}
document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>{view=btn.dataset.view; document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active', b===btn)); document.getElementById('mealsSection').classList.toggle('visible', view==='meals'); document.getElementById('summarySection').classList.toggle('visible', view==='summary'); view==='meals'?renderMeals():renderSummary();}));
document.getElementById('searchInput').addEventListener('input',e=>{search=e.target.value.toLowerCase(); view==='meals'?renderMeals():renderSummary();});
renderMeals();
</script></body></html>