INSERT INTO settings (setting_key, setting_value) VALUES
('event_name', 'Retiro 2027 - ICNV Catedral'),
('max_people', '160'),
('chalet_units', '10'),
('chalet_capacity_per_unit', '6'),
('lodging_capacity', '80'),
('lodging_male_capacity', '40'),
('lodging_female_capacity', '40'),
('price_adult_chale', '700'),
('price_adult_alojamento', '600'),
('price_adult_casa', '600'),
('price_child_chale', '350'),
('price_child_alojamento', '300'),
('price_child_casa', '300'),
('family_discount_percent', '0'),
('registration_fee', '0'),
('max_installments', '10'),
('pix_key', '03.102.014/0001-04'),
('pix_beneficiary', 'Igreja Cristã Nova Vida Catedral'),
('pix_copy_paste', ''),
('payment_receipt_contact', 'Diácono Cláudio'),
('payment_deadline_day', '10'),
('financial_confirmation_note', 'A inscrição só será confirmada mediante aceno financeiro.'),
('reports_email_from', 'noreply@icnvcatedral.local'),
('primary_color', '#0f766e'),
('accent_color', '#0ea5a4'),
('surface_color', '#ffffff'),
('panel_bg_color', '#0b3b39'),
('card_shadow', '0 18px 45px rgba(15,23,42,.08)'),
('font_family', 'Inter, Arial, sans-serif'),
('font_size', '16'),
('font_weight', '400'),
('font_style', 'normal'),
('dashboard_widgets', '{"summary_cards": true, "occupancy_cards": true, "accommodation_chart": true, "finance_chart": true, "status_chart": true, "lodging_gender_chart": true, "recent_groups": true, "recent_activity": true}')
ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value);